### ISSUE TITLE
Make Chrome-HTTP new tab a pop-up window

### ISSUE THREAD

**Issue by san983** [voxbone-workshop/portal-widget#135]
@chadwallacehart commented on [Fri Jan 20 2017](https://github.com/voxbone-workshop/click2vox-com/issues/566)

We were worried pop-ups would be blocked, so we currently open a new tab when a user is on Chrome and the user clicks on a widget that is served from a HTTP site.

See http://jsfiddle.net/1qgzbmqd/ for an example of how a customer is doing this. It appears to work fine for them on Chrome and Firefox without blocking.

---

@san983 commented on [Mon Jan 23 2017](https://github.com/voxbone-workshop/click2vox-com/issues/566#issuecomment-274595396)

Please @chadwallacehart & @fikrifirat, take a look here ➡️  http://jsfiddle.net/1rpthe77/1/, I've deployed this just to https://development.click2vox.com 

https://github.com/voxbone-workshop/click2vox-com/pull/569

That's my quick approach for this and it seems to work good. For sure we need to tweak the look & feel regarding the widget.

---

@chadwallacehart commented on [Mon Jan 23 2017](https://github.com/voxbone-workshop/click2vox-com/issues/566#issuecomment-274644998)

@san983 there are some issues with the pop-up window size when the pop-up dialer is displayed that I posted in slack.

---

@san983 commented on [Tue Jan 24 2017](https://github.com/voxbone-workshop/click2vox-com/issues/566#issuecomment-274835420)

- Adjust the pop-up window size to the active element
- Test throttling the load of the js asset

---

@san983 commented on [Wed Jan 25 2017](https://github.com/voxbone-workshop/click2vox-com/issues/566#issuecomment-275284019)

@chadwallacehart please take a look again into http://jsfiddle.net/1rpthe77/1/
<img width="1098" alt="fullscreen_1_25_17__10_19_pm" src="https://cloud.githubusercontent.com/assets/551102/22316531/7d96f38a-e34c-11e6-852c-926158bc4894.png">

**Comment by chadwallacehart** [comment]
jsfiddle is blocking this now:
![image](https://cloud.githubusercontent.com/assets/6531125/22354508/a7e7f650-e3f3-11e6-8fcf-e44450355cc2.png)

`
Blocked opening 'https://development.click2vox.com/widget/portal-widget/get-html?button_id=5…_default_button_css=true&div_css_class_name=style-a&placement=bottom-right' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.`

@san983 Is there a way to detect this and do a different behavior such as new tab or non-WebRTC?
