### ISSUE TITLE
Hosted page for Chrome-HTTP sites

### ISSUE THREAD

**Issue by chadwallacehart** [voxbone-workshop/portal-widget#78]
Many of Voxbone's customers are not sophisticated with web development and do not have TLS certificates for their websites. When Chrome users use these websites they get a not-supported browser option.

To give WebRTC access to these users we could create a custom URL off of click2vox.com or another site that renders a iframe option in a pop-up widget.

That way when a Chrome users enters a HTTP website, when they click on the button it will load a pop-up with the widget using the styling defined by the button.

The Portal Widget generator should present this as an option for browsers that support WebRTC but require secure origins.

@san983 - please add your notes/thoughts here based on our discussion.

**Comment by san983** [comment]
As discussed with @bnandaku, there are mainly two big steps here:

- [ ] Create and endpoint where the request payload is similar to the `get-code` one, but instead of retrieving a JSON, it should respond with a simple HTML page with the embedded button (of course with the configured details)

- [ ] Make that a user using Chrome, when it is NOT requested with a TLS/SSL certificate and he clicks on the button to place a call. It should open a popup with the button and automatically place the call.

- [ ] After this is up & running, replicate this in Click2Vox.
